# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "VAT Checker"
client_id = "YOUR_CLIENT_ID"
application_url = "https://localhost:3000"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_orders,read_orders,write_checkouts,read_checkouts"

[auth]
redirect_urls = [
  "https://localhost:3000/auth/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "YOUR_DEV_STORE.myshopify.com"
include_config_on_deploy = true

