name = "VAT Checker UI"
uid = "7ac33d28-8ca7-d30c-7213-36719d2d88cb14ab018d"
type = "checkout_ui_extension"
version = "1.0.0"

[base]
targeting = [
  { target = "purchase.checkout.block.render" }
]

[capabilities]
network_access = true
network_access_allowlist = [
  "https://sf-vat-checker-web.vercel.app",
  "https://*.vercel.app",
  "https://*.ngrok.io",
  "https://*.ngrok-free.app"
]

[build]
command = ""
watch = ["src/**/*"]
